# Requirement: "code" CLI installed
code --install-extension FaroSystemAppender constructor
code --install-extension aaron-bond.better-comments
code --install-extension charliermarsh.ruff
code --install-extension Codium.codium
code --install-extension cweijan.dbclient-jdbc
code --install-extension cweijan.vscode-mysql-client2
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dorzey.vscode-sqlfluff
code --install-extension eamodio.gitlens
code --install-extension GitHub.codespaces
code --install-extension github.vscode-github-actions
code --install-extension GitHub.vscode-pull-request-github
code --install-extension GrapeCity.gc-excelviewer
code --install-extension Gruntfuggly.todo-tree
code --install-extension hashicorp.terraform
code --install-extension IronGeek.vscode-env
code --install-extension iterative.dvc
code --install-extension James-Yu.latex-workshop
code --install-extension kawamataryo.copy-python-dotted-path
code --install-extension KnisterPeter.vscode-github
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode.makefile-tools
code --install-extension njpwerner.autodocstring
code --install-extension oderwat.indent-rainbow
code --install-extension phplasma.csv-to-table
code --install-extension pnp.polacode
code --install-extension qwtel.sqlite-viewer
code --install-extension redhat.vscode-yaml
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension tamasfe.even-better-toml
code --install-extension timonwong.shellcheck
code --install-extension twixes.pypi-assistant
code --install-extension wholroyd.jinja
code --install-extension wraith13.zoombar-vscode
code --install-extension yzhang.markdown-all-in-one
